---

apache_config_path: /etc/apache2

apache_packages:
  - apache2
  - apache2-utils

apache_mods_enabled:
  - rewrite.load

apache_mods_available_path: "{{ apache_config_path }}/mods-available"
apache_mods_enabled_path: "{{ apache_config_path }}/mods-enabled"

apache_vhosts_filename: "vhosts.conf"
apache_vhosts_default_filename: "000-default.conf"
apache_vhosts_template: "{{ apache_vhosts_filename }}.j2"
apache_sites_available_path: "{{ apache_config_path }}/sites-available"
apache_sites_enabled_path: "{{ apache_config_path }}/sites-enabled"

#Template data 
apache_listen_ip: "*"
apache_listen_port: 80
apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts:
  - servername: "fp.net"
    documentroot: "/var/www/wordpress"

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymlinks"
